### ISSUE TITLE
helm upgrade failed

### ISSUE THREAD

**Issue by logan2013** [apache/apisix-helm-chart#663] opened 2023-11-13 08:42 UTC
cmd: 
helm upgrade apisix . --set serviceMonitor.enabled=true --namespace apisix

expect:
upgrage success

but result is:
Error: UPGRADE FAILED: cannot patch "apisix-etcd" with kind StatefulSet: StatefulSet.apps "apisix-etcd" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

**Comment by Revolyssup** [comment] 2023-11-13 20:46
I cannot reproduce this. Updating this field should not cause this error. Can you provide more info like the path to the helmchart which you used to upgrade? Because I think you used some local helm chart as you are using local path `.`. Which version of APISIX are you using? Can you try with some official remote repo path like the ones here - https://apache.github.io/apisix-helm-chart/index.yaml

**Comment by Revolyssup** [comment] 2023-12-15 05:44
@logan2013 I am closing the issue. Please reopen if it persists.

**Closed by Revolyssup** 2023-12-15 05:44 UTC
Labels: question
